FORMAT: 1A
HOST: https://gs-sts-cloud-foundry-deployment-shailesh.cfapps.io

# CourseAPI

This is an API to get all the courses available, create new courses, get the courses individually. It can also update and delete a course.

## Employee Collection [/]

### Get all Topics [GET/topics]

+ Response 200 (application/json)

        [
           
                    {
                        "id": "Spring",
                        "name": "Spring boot",
                        "description": "Spring boot description"
                    }, {
                        "id": "Java",
                        "name": "Core Java",
                        "description": "Core Java description"
                    }
        ]


### Get a Topic [GET/topics/{id}]

+ Parameters
    + id(String)
    
+ Response 200 (application/json)

          {
            "id": "Spring",
            "name": "Spring boot",
            "description": "Spring boot description"
          }
    
### Create new Topic[POST/topics]

+ Request (application/json)

          { 
            "id": "JavaEE",
            "name": "Java Enterprise Edition",
            "description": "Java Enterprise Edition description"
          }

+ Response 200
      
         Topic created Successfully!!!

### Update a Topic[PUT/topics/{id}]

+ Parameters
    + id(String)
    
+ Request (application/json)

          { 
            "id": "JavaEE",
            "name": "Updated Java Enterprise Edition",
            "description": "Java Enterprise Edition description"
          }

+ Response 200
      
         Topic updated Successfully!!!

### Delete a Topic[DELETE/topics/{id}]

+ Parameters
    + id(String)
    
+ Response 200
      
         Topic Deleted Successfully!!!